title: <p align="center"> Ariana-Lea Zuber </p> # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here

description: # your text below
  <p align="center">
  Master of Informatics (MInf) graduated at Faculty of Organization and Informatics in Varaždin, 
  majored in Information and Software Engineering, with a goal of further 
  professional and personal development. 
  </p>
  <br><br>
  <a href="https://github.com/alzuber">View My GitHub Profile</a> 
  
  
theme: jekyll-theme-minimal
