title: Ariana-Lea Zuber # your name (or website title) here
logo: "/images/image.png?raw=true height=270px" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate student at the Faculty of Organization and Informatics in Varaždin, 
  majoring in Information and Software Engineering, with a goal of further 
  professional and personal development. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
