title: Ariana-Lea Zuber # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here

description: # your text below
  Graduate student at the Faculty of Organization and Informatics in Varaždin, 
  majoring in Information and Software Engineering, with a goal of further 
  professional and personal development. 
  <br><br>
  <br><br>
  <br><br>
  <a href="https://github.com/alzuber">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal
